In [272]:
import json

import pandas as pd

from pandas import json_normalize

import matplotlib.pyplot as plt

import numpy as np

from mpl_toolkits.axes_grid1.inset_locator import inset_axes

from matplotlib.projections import get_projection_class

from matplotlib.patches import Arc

In [273]:
with open (r"C:\Users\mdefores\OneDrive - Capgemini\Desktop\FFR\match france-angleterre.json","r",encoding='utf-8', errors='ignore') as f:
    obj=json.load(f,strict=False)

df = json_normalize(obj)

In [274]:
df=df.drop(['StatEvent','GameMinutes','GameSeconds','VidRef','X','Y','Zone','Metres','PhaseNum','TeamFinalScore','GameId','MT','X.sens','Y.sens','TeamIdAdv','Zone.longueur','Num','order','ArretPen','NumPoss','NumSeq','Duree','TransiPoss'],axis=1)

In [275]:
df[df['PlayerId']==769].groupby(['TeamId','PlayerName']).mean()

                      Colonne1  PlayerId       StatId          nX          nY
TeamId PlayerName
1116   Gael Fickou  563.333333     769.0  6471.944444  516.472222  361.305556

In [276]:
df.groupby(['TeamId','PlayerName']).mean()

                              Colonne1  PlayerId        StatId          nX  \
TeamId PlayerName
1114   Anthony Watson       514.384615      38.0   7048.384615  613.461538
       Ben Earl            1033.600000   36151.0   9159.900000  576.000000
       Ben Youngs           537.143617     314.0   5068.952128  625.079787
       Billy Vunipola       528.714286      75.0   8521.166667  594.261905
       Charlie Ewels        327.600000    3340.0   8141.133333  511.066667
       Dan Robson          1077.500000     101.0   5027.000000  295.500000
       Elliot Daly          958.090909     346.0   7419.636364  456.727273
       Ellis Genge         1043.500000   13530.0  10255.500000  699.750000
       George Ford          586.935897      33.0   5277.679487  561.384615
       Henry Slade          446.583333     183.0   6328.166667  636.666667
       Jamie George        1033.166667      71.0   8507.333333  752.166667
       Jonny May            606.294118     330.0   8391.500000  566.441176
       Kyle Sinckler        494.850000     304.0   8659.100000  649.800000
       Luke Cowan-Dickie    521.052632     468.0   9665.789474  631.631579
       Mako Vunipola        512.850000      86.0   8635.750000  691.900000
       Mark Wilson          521.666667      19.0   7952.222222  746.333333
       Maro Itoje           718.769231     513.0   7051.000000  592.615385
       Max Malins           519.290323   33963.0   7867.387097  474.096774
       Ollie Lawrence      1046.500000   41277.0  10255.500000  545.500000
       Owen Farrell         473.651163      79.0   4909.000000  608.581395
       Tom Curry            597.857143   35976.0   8402.857143  605.464286
       Will Stuart         1061.000000   33772.0  10255.500000  759.500000
1116   Antoine Dupont       513.086614    4059.0   5380.055118  536.125984
       Brice Dulin          601.052632     832.0   6391.982456  437.385965
       Cameron Woki        1084.000000   37187.0     15.000000  727.000000
       Camille Chat        1087.500000    6767.0   5011.000000  728.500000
       Charles Ollivon      552.533333     526.0   8176.666667  589.066667
       Cyril Baille         403.700000     750.0   6585.900000  589.500000
       Cyril Cazeaux        841.000000    5099.0     36.000000  420.000000
       Damian Penaud        630.933333    6765.0   5381.133333  564.400000
       Dorian Aldegheri    1068.000000    1088.0  10022.000000  428.000000
       Dylan Cretin         492.250000   35968.0   5969.166667  487.916667
       Gael Fickou          563.333333     769.0   6471.944444  516.472222
       Gregory Alldritt     633.815789   41370.0   7786.842105  420.342105
       Jean-Baptiste Gros  1089.500000   41599.0  10255.500000  731.000000
       Julien Marchand      525.846154    1086.0   7856.230769  540.846154
       Matthieu Jalibert    556.888889   38098.0   5261.539683  445.333333
       Mohamed Haouas       461.533333   39074.0  10207.800000  671.333333
       Paul Willemse        457.833333    3155.0  10175.166667  393.500000
       Romain Taofifenua    378.466667     546.0   6779.666667  608.933333
       Teddy Thomas         480.909091     880.0   6919.772727  571.818182
       Virimi Vakatawa      481.736842   20954.0   7510.578947  596.842105

                                   nY
TeamId PlayerName
1114   Anthony Watson      592.538462
       Ben Earl            315.900000
       Ben Youngs          292.159574
       Billy Vunipola      261.857143
       Charlie Ewels       315.666667
       Dan Robson          164.000000
       Elliot Daly         270.818182
       Ellis Genge         149.500000
       George Ford         303.679487
       Henry Slade         342.291667
       Jamie George        493.666667
       Jonny May           187.058824
       Kyle Sinckler       333.150000
       Luke Cowan-Dickie   282.210526
       Mako Vunipola       329.950000
       Mark Wilson         323.555556
       Maro Itoje          350.923077
       Max Malins          307.741935
       Ollie Lawrence      573.000000
       Owen Farrell        315.837209
       Tom Curry           372.178571
       Will Stuart         519.750000
1116   Antoine Dupont      369.779528
       Brice Dulin         350.000000
       Cameron Woki        565.000000
       Camille Chat        602.500000
       Charles Ollivon     377.133333
       Cyril Baille        352.650000
       Cyril Cazeaux       567.000000
       Damian Penaud       599.600000
       Dorian Aldegheri    287.000000
       Dylan Cretin        264.750000
       Gael Fickou         361.305556
       Gregory Alldritt    372.078947
       Jean-Baptiste Gros  517.500000
       Julien Marchand     250.538462
       Matthieu Jalibert   369.174603
       Mohamed Haouas      330.400000
       Paul Willemse       377.666667
       Romain Taofifenua   311.533333
       Teddy Thomas        114.500000
       Virimi Vakatawa     356.578947

In [207]:
df.head(5) #shows us the first five

,Colonne1,PlayerId,StatEvent,PlayerName,StatId,StatName,GameMinutes,GameSeconds,VidRef,X,...,DistCum,RuckNb,OrigineRuck,Cote,Ruck.largeur,Ruck.longueur,Ruck.Next,sensRuck,DureeSeqPen,OffDef
0,1,75,,Billy Vunipola,10007,Receipts,,4,367,162,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
1,2,75,,Billy Vunipola,10504,Ruck,,7,442,161,...,NA,1,Start,NA,NA,NA,Kick,NA,NA,NA
2,3,314,,Ben Youngs,10007,Receipts,,15,651,153,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
3,4,314,,Ben Youngs,47,Kick,,16,673,149,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,5,832,,Brice Dulin,10007,Receipts,,20,780,413,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA

In [240]:
player_dict = {}

klist = []

for player in df.iloc[:,3]:
    p = player[:]
    PlayerName = p[:]
    klist.append(PlayerName)
    

xlist = df.iloc[:,10].values

ylist = df.iloc[:,12].values

#xlist = [0,42,42,42,42,62,62,85,85,97,97]

#ylist = [45,15,30,55,75,30,60,30,55,22,68]

for x,y,z in zip(xlist, ylist, klist):

    entry = {z:[x,y]}

    player_dict.update(entry)

In [209]:
df.iloc[0,3]

'Billy Vunipola'

In [210]:
player_dict

{'Billy Vunipola': [573, 414],
 'Ben Youngs': [550, 161],
 'Brice Dulin': [798, 103],
 'Antoine Dupont': [766, 192],
 'Cyril Baille': [303, 415],
 'Gael Fickou': [721, 346],
 'Charles Ollivon': [743, 609],
 'Matthieu Jalibert': [710, 269],
 'Virimi Vakatawa': [752, 260],
 'Romain Taofifenua': [129, 259],
 'Dylan Cretin': [327, 629],
 'Teddy Thomas': [131, 178],
 'Gregory Alldritt': [775, 193],
 'Max Malins': [208, 291],
 'Charlie Ewels': [705, 379],
 'George Ford': [524, 314],
 'Mako Vunipola': [574, 242],
 'Jonny May': [448, 131],
 'Tom Curry': [231, 522],
 'Anthony Watson': [188, 680],
 'Owen Farrell': [474, 675],
 'Henry Slade': [127, 490],
 'Kyle Sinckler': [824, 194],
 'Luke Cowan-Dickie': [803, 505],
 'Mark Wilson': [697, 90],
 'Damian Penaud': [449, 667],
 'Mohamed Haouas': [756, 601],
 'Maro Itoje': [309, 160],
 'Paul Willemse': [463, 314],
 'Julien Marchand': [752, 257],
 'Cyril Cazeaux': [420, 567],
 'Elliot Daly': [710, 257],
 'Ben Earl': [218, 522],
 'Jamie George': [956, 590],
 'Ellis Genge': [561, 156],
 'Ollie Lawrence': [572, 565],
 'Will Stuart': [960, 552],
 'Dorian Aldegheri': [428, 287],
 'Dan Robson': [290, 168],
 'Cameron Woki': [727, 565],
 'Camille Chat': [727, 600],
 'Jean-Baptiste Gros': [760, 500]}

In [285]:
def Passer(player):

    local_df = df.copy(deep=True)

    local_df = local_df[local_df["StatName"]=="Passe"]

    local_df = local_df[local_df["PlayerName"]==player]

    local_df = local_df.dropna(axis=1, how="all")



    df1 = local_df[['AnglePasse','LongueurPasse']].copy()



    bins = np.linspace(-np.pi,np.pi,10)



    df1['binned'] = pd.cut(local_df['AnglePasse'], bins, include_lowest=True, right = True)

    df1["Bin_Mids"] = df1["binned"].apply(lambda x: x.mid)

    df1 = df1[:-1]



    A= df1.groupby("Bin_Mids", as_index=False)["LongueurPasse"].mean()

    A = A.dropna(0)



    return A
    print(bins)

In [286]:
a = Passer("Billy Vunipola")

TypeError: '<' not supported between instances of 'float' and 'str'